on:
  push:
    branches:
      - staging
name: 🚀 Deploy staging website on push
jobs:
  web-deploy:
    name: 🎉 Deploy to staging
    runs-on: ubuntu-latest
    concurrency: staging
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER_STAGING }}
          port: 21
          protocol: ftp
          username: ${{ secrets.FTP_USERNAME_STAGING }}
          password: ${{ secrets.FTP_PASSWORD_STAGING }}
          server-dir: ./
